name: CI
on: [push, pull_request]
jobs:

  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install node modules
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Run build
        run: yarn build
      - name: Run test
        run: yarn test
